name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: 24f2006074@ds.study.iitm.ac.in
        run: echo "Hello, world!"
        
      - name: Checkout code
        uses: actions/checkout@v2
